name: clustal_env
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python
    - numpy
    - biopython
    - matplotlib
    - networkx
    # Linters and formateurs
    - pycodestyle
    - pydocstyle
    - pylint
    - black
    - ruff
